### ISSUE TITLE
Feature request: add an option to switch Enter and Shift-Enter shortcuts

### ISSUE THREAD

**Issue by IgorKrupenja** [falsandtru/spatialnavigation#1]
Thank you for this great extension, very useful!

I would like to request a setting to change Enter and Shift-Enter shortcuts, so that default action on Enter could be configured to open the link in the same tab.

**Comment by falsandtru** [comment]
Unfortunately, I don't know how to make a configurable extension. And I ended the development of this extension. So I won't do it.
